"""Generate the Clawdmeter Claude Code plugin's sprite module from assets/sprites.

The Clawdmeter plugin (claude-code/clawdmeter) draws Clawd in Claude Code. Its
frames are not a second copy of the art kept by hand: this script derives
claude-code/clawdmeter/hooks/sprites.ts from the same assets/sprites PNGs and
manifest the app plays, so the two can never drift (tests/test_band_sprites.py
fails if the committed file differs from what this script would write).

The Clawd mascot is (c) Anthropic PBC; see NOTICE for the carve-out this file
is covered by.

Usage (repo root):
    .venv\\Scripts\\python.exe tools\\build_band_sprites.py          # rewrite sprites.ts
    .venv\\Scripts\\python.exe tools\\build_band_sprites.py --check  # exit 1 if stale
"""
from __future__ import annotations

import json
import pathlib
import sys

from PySide6.QtGui import QImage

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPRITES = ROOT / "assets" / "sprites"
OUT = ROOT / "claude-code" / "clawdmeter" / "hooks" / "sprites.ts"

# The animations the plugin plays; must match ANIMS in claude-code/clawdmeter/hooks/clawd.ts.
ANIMATIONS = ["work coding", "work think", "idle look around", "idle blink", "expression surprise", "idle breathe"]

HEADER = """\
// GENERATED by tools/build_band_sprites.py from assets/sprites -- do not edit.
// The Clawd mascot is (c) Anthropic PBC and is NOT covered by the MIT License:
// see NOTICE. Each frame is 20x20 cells, row by row: '.' is clear, 'A'..
// index the palette; `ms` is the manifest's hold time.

export type Frame = { px: string; ms: number }

export const SPRITES: { palette: string[]; anims: Record<string, Frame[]> } = """


def build() -> str:
    manifest = json.loads((SPRITES / "manifest.json").read_text(encoding="utf-8"))
    palette: list[str] = []
    anims: dict[str, list[dict]] = {}
    for name in ANIMATIONS:
        anim = manifest["animations"][name]
        frames = []
        for fr in anim["frames"]:
            img = QImage(str(SPRITES / fr["file"]))
            if img.isNull() or img.width() != 20 or img.height() != 20:
                raise SystemExit(f"{fr['file']}: expected a 20x20 image")
            img = img.convertToFormat(QImage.Format_ARGB32)
            cells = []
            for y in range(20):
                for x in range(20):
                    c = img.pixelColor(x, y)
                    if c.alpha() < 128:
                        cells.append(".")
                        continue
                    hexc = c.name()
                    if hexc not in palette:
                        palette.append(hexc)
                    cells.append(chr(65 + palette.index(hexc)))
            frames.append({"px": "".join(cells), "ms": fr["hold_ms"]})
        anims[anim["slug"]] = frames
    if len(palette) > 26:
        raise SystemExit(f"{len(palette)} colours: the one-letter encoding holds 26")
    return HEADER + json.dumps({"palette": palette, "anims": anims}, separators=(",", ":")) + "\n"


def main(argv: list[str]) -> int:
    text = build()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is stale: run tools/build_band_sprites.py")
            return 1
        print(f"{OUT.relative_to(ROOT)} is up to date")
        return 0
    OUT.write_bytes(text.encode("utf-8"))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
